# docker-compose.yml
version: '3'

services:
  express-app:
    build: .
    container_name: express-app
    ports:
      - "3000:3000"
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - express-app
